export const languages = ['zh', 'en', 'ja'];
const catalog = {
  en: {
    title: 'HiddenShade', subtitle: 'A city of shadows. A way through.', edition: 'AN ENDLESS STEALTH ESCAPE', start: 'Enter the maze', continue: 'Continue · Floor {floor}', floor: 'Floor', time: 'Time', detections: 'Sightings', hideUses: 'Hides used', pause: 'Pause', resume: 'Resume', retry: 'Try this floor again', next: 'Descend to floor {floor}', home: 'Title screen', settings: 'Settings', language: 'Language', music: 'Music', sfx: 'Sound effects', masterVolume: 'Master volume', musicVolume: 'Music volume', sfxVolume: 'Effects volume', controls: 'Controls', up: 'Move up', down: 'Move down', left: 'Move left', right: 'Move right', interact: 'Hide / emerge', hidden: 'Hidden · observe before emerging', emerging: 'Emerging…', safe: 'Stay beyond their sight', alert: 'You are being watched', pauseKey: 'Pause', remap: 'Select a key, then press its replacement.', pressKey: 'Press a key…', duplicateKey: 'That key is already assigned.', keyArrowUp: '↑', keyArrowDown: '↓', keyArrowLeft: '←', keyArrowRight: '→', keySpace: 'Space', keyEscape: 'Esc', keyEnter: 'Enter', keyTab: 'Tab', keyBackspace: 'Backspace', keyShift: 'Shift', keyControl: 'Ctrl', keyAlt: 'Alt', keyBracketLeft: '[', keyBracketRight: ']', keySemicolon: ';', keyQuote: "'", keyComma: ',', keyPeriod: '.', keySlash: '/', keyBackslash: '\\', keyMinus: '−', keyEqual: '=', keyBackquote: '`',
    memory: 'Memory map', records: 'Local records', statistics: 'Statistics', help: 'Field guide', highestFloor: 'Highest floor', bestStars: 'Best rating', escapes: 'Escapes', catches: 'Captures', playTime: 'Time in the maze', empty: 'Your story has not begun. Escape a floor to leave your first record.', localOnly: 'Stored on this device. No account. No leaderboard.', guideTitle: 'Light reveals. Shadows protect.', guideMove: 'WASD or arrow keys move in screen directions. Drag the joystick or tap the directional pad.', guideHide: 'Press Space near a hiding place to enter or leave. You cannot move while hidden. Emerging takes a moment.', guideSight: 'Walls block sight. A guard’s amber suspicion gives you time to slip away before pursuit.', guideMemory: 'Explored passages stay on your memory map. Guards only appear where you can see them.', guideExit: 'Find the warm-lit door. A clean, quick escape with few hiding stops earns three stars.', guidePause: 'Esc or P pauses. Use + / −, the zoom buttons, or pinch to change your view.', pausedTitle: 'Between footsteps', pausedText: 'The city waits. Time and every patrol are frozen.', caughtTitle: 'The shadows gave you away', caughtText: 'Your route is unchanged. Learn their rhythm and try again.', escapedTitle: 'A door into the dark', escapedText: 'Another floor behind you. Your progress is saved.', rating3: 'A ghost in the city', rating2: 'A careful escape', rating1: 'You made it through', guardDetail: 'Spotted by guard {guard}', lastSeen: 'Last seen at ({x}, {y})', captureAt: 'Caught at ({x}, {y})', share: 'Save a share card', zoomIn: 'Zoom in', zoomOut: 'Zoom out', saveTools: 'Carry your progress', exportFile: 'Download JSON', exportCode: 'Show save code', import: 'Import save', importTitle: 'Bring your journey back', importText: 'Choose a JSON file or paste a JSON / Base64 save below. Nothing changes until you confirm.', chooseFile: 'Choose JSON file', saveCode: 'Save data / code', preview: 'Preview import', confirm: 'Back up & import', cancel: 'Cancel', backup: 'Your current save is automatically backed up before replacement.', previewTitle: 'Save preview', updated: 'Last saved', invalidSave: 'This save could not be read. Check the file or paste the complete code.', storageFailure: 'Device storage is unavailable. Progress may not be saved. Export a copy before leaving.', copied: 'Save code ready. Select and copy it to keep a portable backup.', back: 'Back', status: 'Status', stars: 'Rating', close: 'Close', saveRestored: 'Your backup has been restored.', scoreThreshold: 'Three stars: under 4 minutes, no sightings, at most 2 hides.', downloadHint: 'JSON and save codes contain the same progress.', importFailed: 'Import failed. Your current progress has not been replaced.'
  },
  zh: {
    title: '藏影迷城', subtitle: '穿過暗影之城，尋找一線出口。', edition: '無盡潛行・迷宮逃脫', start: '進入迷城', continue: '繼續旅程・第 {floor} 層', floor: '層數', time: '時間', detections: '被發現', hideUses: '藏匿次數', pause: '暫停', resume: '繼續', retry: '重來這一層', next: '前往第 {floor} 層', home: '返回標題', settings: '設定', language: '語言', music: '背景音樂', sfx: '音效', masterVolume: '總音量', musicVolume: '音樂音量', sfxVolume: '音效音量', controls: '操作設定', up: '向上移動', down: '向下移動', left: '向左移動', right: '向右移動', interact: '藏匿／現身', hidden: '藏匿中・觀察後再現身', emerging: '現身中…', safe: '避開巡邏者的視線', alert: '你正被注視', pauseKey: '暫停', remap: '選取按鍵後，按下新的替代鍵。', pressKey: '請按下新按鍵…', duplicateKey: '這個按鍵已被使用。', keyArrowUp: '↑', keyArrowDown: '↓', keyArrowLeft: '←', keyArrowRight: '→', keySpace: '空白鍵', keyEscape: '離開鍵', keyEnter: '確認鍵', keyTab: '定位鍵', keyBackspace: '退格鍵', keyShift: '上檔鍵', keyControl: '控制鍵', keyAlt: '替代鍵', keyBracketLeft: '[', keyBracketRight: ']', keySemicolon: ';', keyQuote: "'", keyComma: ',', keyPeriod: '.', keySlash: '/', keyBackslash: '\\', keyMinus: '−', keyEqual: '=', keyBackquote: '`',
    memory: '記憶地圖', records: '本機紀錄', statistics: '統計', help: '潛行指南', highestFloor: '最高到達層', bestStars: '最佳評價', escapes: '逃脫次數', catches: '被抓次數', playTime: '累計遊玩時間', empty: '旅程尚未開始。逃出第一層，留下你的足跡。', localOnly: '僅存於此裝置。無帳號，無線上排行。', guideTitle: '光會暴露你，暗影會庇護你。', guideMove: '使用 WASD 或方向鍵依畫面方向移動，也可拖曳搖桿或點按方向鍵組。', guideHide: '在藏匿點附近按空白鍵進入或離開。藏匿時不能移動，現身需要一點時間。', guideSight: '牆壁會阻擋視線。巡邏者發出琥珀色警戒時，趁追捕開始前脫身。', guideMemory: '探索過的通道會留在記憶地圖。巡邏者只在你能看見的地方顯示。', guideExit: '尋找暖光之門。快速、零驚動且少用藏匿的逃脫，可獲得三星。', guidePause: '按離開鍵或 P 暫停。使用 ＋／－、縮放按鈕或雙指手勢調整視角。', pausedTitle: '腳步之間', pausedText: '城市等待著。計時與所有巡邏都已凍結。', caughtTitle: '暗影暴露了你', caughtText: '路線不變。記住巡邏的節奏，再試一次。', escapedTitle: '通往深處的門', escapedText: '又一層留在身後。進度已儲存。', rating3: '迷城中的幽影', rating2: '謹慎的逃脫', rating1: '成功逃出生天', guardDetail: '被巡邏者 {guard} 發現', lastSeen: '最後目擊位置（{x}，{y}）', captureAt: '被抓位置（{x}，{y}）', share: '儲存分享卡', zoomIn: '放大', zoomOut: '縮小', saveTools: '帶走你的旅程', exportFile: '下載 JSON', exportCode: '顯示存檔碼', import: '匯入存檔', importTitle: '接續你的旅程', importText: '選取 JSON 檔案，或貼上 JSON／Base64 存檔碼。確認前不會變更進度。', chooseFile: '選取 JSON 檔案', saveCode: '存檔資料／存檔碼', preview: '預覽匯入', confirm: '備份並匯入', cancel: '取消', backup: '覆蓋前會自動備份目前的存檔。', previewTitle: '存檔預覽', updated: '最後儲存時間', invalidSave: '無法讀取此存檔。請檢查檔案，或貼上完整存檔碼。', storageFailure: '裝置儲存空間無法使用，進度可能無法保存。離開前請匯出備份。', copied: '存檔碼已備妥。請選取並複製，保留可攜式備份。', back: '返回', status: '狀態', stars: '評價', close: '關閉', saveRestored: '已還原備援存檔。', scoreThreshold: '三星條件：四分鐘內、零次被發現、藏匿不超過兩次。', downloadHint: 'JSON 檔與存檔碼包含相同的遊玩進度。', importFailed: '匯入失敗，目前進度未被覆蓋。'
  },
  ja: {
    title: '影隠れの迷城', subtitle: '影の街を抜け、出口を探せ。', edition: '終わりなきステルス脱出', start: '迷城へ入る', continue: '続きから・第 {floor} 階', floor: '階層', time: '時間', detections: '発見回数', hideUses: '隠れた回数', pause: '一時停止', resume: '再開', retry: 'この階をやり直す', next: '第 {floor} 階へ進む', home: 'タイトルへ', settings: '設定', language: '言語', music: '音楽', sfx: '効果音', masterVolume: '全体音量', musicVolume: '音楽音量', sfxVolume: '効果音量', controls: '操作設定', up: '上へ移動', down: '下へ移動', left: '左へ移動', right: '右へ移動', interact: '隠れる／出る', hidden: '潜伏中・周囲を見てから出よう', emerging: '姿を現しています…', safe: '見張りの視線を避けよう', alert: '見られています', pauseKey: '一時停止', remap: '変更するキーを選び、新しいキーを押してください。', pressKey: '新しいキーを押してください…', duplicateKey: 'そのキーは使用されています。', keyArrowUp: '↑', keyArrowDown: '↓', keyArrowLeft: '←', keyArrowRight: '→', keySpace: 'スペース', keyEscape: 'エスケープ', keyEnter: 'エンター', keyTab: 'タブ', keyBackspace: 'バックスペース', keyShift: 'シフト', keyControl: 'コントロール', keyAlt: 'オルト', keyBracketLeft: '[', keyBracketRight: ']', keySemicolon: ';', keyQuote: "'", keyComma: ',', keyPeriod: '.', keySlash: '/', keyBackslash: '\\', keyMinus: '−', keyEqual: '=', keyBackquote: '`',
    memory: '記憶の地図', records: '端末の記録', statistics: '統計', help: '潜行の手引き', highestFloor: '最高到達階', bestStars: '最高評価', escapes: '脱出回数', catches: '捕まった回数', playTime: '累計プレイ時間', empty: '旅はまだ始まっていません。最初の階を脱出し、足跡を残しましょう。', localOnly: 'この端末にのみ保存。アカウントやオンライン順位はありません。', guideTitle: '光は暴き、影は守る。', guideMove: 'WASD または矢印キーで画面方向に移動。スティックのドラッグや方向ボタンでも操作できます。', guideHide: '隠れ場所の近くでスペースを押すと出入りできます。潜伏中は動けず、出るには少し時間が必要です。', guideSight: '壁が視線を遮ります。琥珀色の警戒が出たら、追跡が始まる前に逃げましょう。', guideMemory: '探索した通路は記憶の地図に残ります。見張りは見える場所にだけ表示されます。', guideExit: '暖かな光の扉を探しましょう。素早く、発見されず、少ない潜伏で脱出すれば三つ星です。', guidePause: 'エスケープまたは P で一時停止。＋／−、拡大縮小ボタン、ピンチで視点を調整できます。', pausedTitle: '足音の合間', pausedText: '街は待っています。時間も見張りも止まりました。', caughtTitle: '影に見放された', caughtText: '道は変わりません。巡回のリズムを覚え、もう一度。', escapedTitle: '闇へ続く扉', escapedText: 'また一つの階を越えました。進行状況は保存済みです。', rating3: '迷城の幽影', rating2: '慎重な脱出', rating1: '無事に脱出', guardDetail: '見張り {guard} に発見されました', lastSeen: '最後の目撃地点（{x}, {y}）', captureAt: '捕まった地点（{x}, {y}）', share: 'シェアカードを保存', zoomIn: '拡大', zoomOut: '縮小', saveTools: '旅を持ち運ぶ', exportFile: 'JSON をダウンロード', exportCode: 'セーブコードを表示', import: 'セーブを読み込む', importTitle: '旅の続きを取り戻す', importText: 'JSON ファイルを選ぶか、JSON／Base64 セーブコードを貼り付けてください。確認するまでは変更されません。', chooseFile: 'JSON ファイルを選択', saveCode: 'セーブデータ／コード', preview: '読み込みのプレビュー', confirm: 'バックアップして読み込む', cancel: 'キャンセル', backup: '置き換える前に現在のセーブを自動バックアップします。', previewTitle: 'セーブのプレビュー', updated: '最終保存日時', invalidSave: 'セーブを読み取れません。ファイルを確認するか、コード全体を貼り付けてください。', storageFailure: '端末の保存領域を利用できません。終了前にデータを書き出してください。', copied: 'セーブコードが用意できました。選択してコピーし、バックアップを保管してください。', back: '戻る', status: '状態', stars: '評価', close: '閉じる', saveRestored: 'バックアップを復元しました。', scoreThreshold: '三つ星の条件：4 分未満、発見ゼロ、潜伏 2 回以下。', downloadHint: 'JSON とセーブコードには同じ進行状況が入っています。', importFailed: '読み込みに失敗しました。現在の進行状況は置き換えられていません。'
  }
};
Object.assign(catalog.en, { source: 'Source code', restoreBackup: 'Restore backup', storageError: catalog.en.storageFailure, importError: catalog.en.invalidSave, audioError: 'Audio could not start. You can still play in silence.', loading: 'Opening the city…', shareFloor: 'Reached floor {floor}', shareStats: '{time} · {stars} stars', error: 'Something went wrong.' });
Object.assign(catalog.zh, { source: '原始碼', restoreBackup: '還原備份', storageError: catalog.zh.storageFailure, importError: catalog.zh.invalidSave, audioError: '音訊無法啟動，你仍可靜音遊玩。', loading: '迷城開啟中…', shareFloor: '抵達第 {floor} 層', shareStats: '{time}・{stars} 星', error: '發生錯誤。' });
Object.assign(catalog.ja, { source: 'ソースコード', restoreBackup: 'バックアップを復元', storageError: catalog.ja.storageFailure, importError: catalog.ja.invalidSave, audioError: '音声を開始できません。音なしでプレイできます。', loading: '迷城を開いています…', shareFloor: '第 {floor} 階に到達', shareStats: '{time}・{stars} つ星', error: 'エラーが発生しました。' });
let language = 'en';
try { const query = new URL(location.href).searchParams.get('lang'); if (languages.includes(query)) language = query; } catch { /* Non-browser consumers use English. */ }
export function getLanguage() { return language; }
export function setLanguage(lang) {
  if (!languages.includes(lang)) return false;
  language = lang;
  if (typeof document !== 'undefined') {
    document.documentElement.lang = lang === 'zh' ? 'zh-Hant' : lang;
    document.title = t('title');
  }
  if (typeof location !== 'undefined') {
    const url = new URL(location.href); url.searchParams.set('lang', lang);
    history.replaceState(history.state, '', url);
    window.dispatchEvent(new CustomEvent('hiddenshade:language', { detail: lang }));
  }
  return true;
}
export function t(key, params = {}) {
  const text = catalog[language][key] ?? catalog.en[key] ?? key;
  return text.replace(/\{(\w+)\}/g, (match, name) => params[name] === undefined ? match : String(params[name]));
}
