import { readdir, readFile, writeFile } from 'node:fs/promises';
import { createHash } from 'node:crypto';
const roots = ['assets','src','vendor/xyz/dist'];
const files = ['index.html','app.js','styles.css','favicon.ico','manifest.webmanifest'];
async function visit(dir) {
  for (const entry of await readdir(dir,{withFileTypes:true})) {
    const name = `${dir}/${entry.name}`;
    if (entry.isDirectory()) await visit(name);
    else if (/\.(?:js|json|svg|png|ico|css|woff2)$/.test(name)) files.push(name);
  }
}
for (const root of roots) await visit(root);
files.sort();
const digest = createHash('sha256');
for (const file of files) { digest.update(file); digest.update(await readFile(file)); }
const version = digest.digest('hex').slice(0,16);
await writeFile('cache-manifest.js', `// Generated by npm run cache from every offline runtime asset.\nself.HIDDEN_SHADE_CACHE = ${JSON.stringify({version,files})};\n`);
console.log(`Offline inventory ${version}: ${files.length} assets`);
